In [1]:
import tensorflow as tf

In [5]:
# Initialize a TensorFlow constant with a value of 4, specifying the shape as (1, 1) and data type as float32
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)

# Print the value of the tensor 'x'
print(x)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [6]:
# Initialize a TensorFlow constant with a 2x3 matrix and a specified shape of (2, 3)
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))

# Print the value of the tensor 'x'
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
# Create a 3x3 identity matrix using TensorFlow's tf.eye() function
# tf.eye(n) generates a square identity matrix of size n, where diagonal elements are 1 and off-diagonal elements are 0
x = tf.eye(3)

# Print the value of the identity matrix 'x'
print(x)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
# Create a 3x2x5 tensor filled with zeros using TensorFlow's tf.zeros() function
# tf.zeros(shape) generates a tensor of the specified shape with all elements initialized to 0
x = tf.zeros((3, 2, 5))

# Print the value of the tensor 'x'
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [9]:
# Create a 2x2 tensor with random values uniformly distributed between minval (0) and maxval (1) using tf.random.uniform()
# tf.random.uniform(shape, minval, maxval) generates a tensor of the specified shape with random values in the given range
x = tf.random.uniform((2, 2), minval=0, maxval=1)

# Print the value of the tensor 'x'
print(x)


tf.Tensor(
[[0.05759704 0.96135664]
 [0.22801352 0.42516148]], shape=(2, 2), dtype=float32)


In [10]:
# Create a 3x3 tensor with random values drawn from a normal distribution with mean 0 and standard deviation 1 using tf.random.normal()
# tf.random.normal(shape, mean, stddev) generates a tensor of the specified shape with values from a normal (Gaussian) distribution
x = tf.random.normal((3, 3), mean=0, stddev=1)

# Cast the tensor 'x' to a different data type (float64) using tf.cast()
# tf.cast(tensor, dtype) changes the data type of the tensor to the specified dtype
print(tf.cast(x, dtype=tf.float64))


tf.Tensor(
[[ 0.65910429 -0.89214152 -0.86553907]
 [-2.17276621  0.73703843  0.86458117]
 [ 1.19924748  0.49931648 -1.22028172]], shape=(3, 3), dtype=float64)


In [11]:
# Create a 1D tensor with values ranging from 0 to 8 (not including 9) using tf.range()
x = tf.range(9)

# Create a 1D tensor starting from 0, up to (but not including) 10, with a step size of 2 using tf.range()
# tf.range(start, limit, delta) generates a sequence of values with the specified start, end, and step size
x = tf.range(start=0, limit=10, delta=2)

# Print the value of the tensor 'x'
print(x)


tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


## Maths

In [12]:
# Initialize two 1D tensors (vectors) with constant values
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])


In [14]:
# Add the two tensors 'x' and 'y' using tf.add()
z = tf.add(x, y)

# Alternatively, add the two tensors using the '+' operator, which is equivalent to tf.add()
z = x + y
print(z)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [15]:
# Subtract tensor 'y' from tensor 'x' using tf.subtract()
z = tf.subtract(x, y)

# Alternatively, subtract tensor 'y' from tensor 'x' using the '-' operator, which is equivalent to tf.subtract()
z = x - y
print(z)


tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [16]:
# Divide tensor 'x' by tensor 'y' using tf.divide()
z = tf.divide(x, y)

# Alternatively, divide tensor 'x' by tensor 'y' using the '/' operator, which is equivalent to tf.divide()
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [17]:
# Multiply tensor 'x' by tensor 'y' using tf.multiply()
z = tf.multiply(x, y)

# Alternatively, multiply tensor 'x' by tensor 'y' using the '*' operator, which is equivalent to tf.multiply()
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [18]:
# Compute the tensor dot product of 'x' and 'y' using tf.tensordot()
# tf.tensordot(x, y, axes) computes the dot product along specified axes
# In this case, axes=1 performs a dot product over the last dimension of 'x' and the first dimension of 'y'
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


## Lets understand this 'tf.tensordot' with a use case

### Scenario: Combining Image Features for Classification

Imagine you are a detective trying to identify objects in images using clues from the picture. You have different types of clues:

1. **Edges**: Shows the boundaries of objects (like the outline of a cat’s ears).
2. **Textures**: Reveals the surface patterns (like the fur of the cat).
3. **Colors**: Captures the color information (like the cat's color).

### How It Works

1. **Feature Maps**: Each image is analyzed to get feature maps for edges, textures, and colors. These feature maps are 4x4 grids showing details about the image.

2. **Weights**: Each type of clue is assigned a weight based on how important it is for identifying the image:
   - **Edges**: Weight = 0.5
   - **Textures**: Weight = 1.0
   - **Colors**: Weight = 1.5

3. **Combine Clues**: Multiply each feature map by its weight and add them together to get a combined score for each image.


In [20]:
import tensorflow as tf

# Define synthetic feature maps for 2 images (shape: [2, 3, 4, 4])
feature_maps = tf.constant([
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],  # Edges
        [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]],        # Textures
        [[1, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2]]         # Colors
    ],
    [
        [[2, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13], [14, 15, 16, 17]],  # Edges
        [[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4], [5, 5, 5, 5]],        # Textures
        [[2, 3, 2, 3], [2, 3, 2, 3], [2, 3, 2, 3], [2, 3, 2, 3]]         # Colors
    ]
], dtype=tf.float32)

# Define weights for each feature type (shape: [3])
weights = tf.constant([0.5, 1.0, 1.5], dtype=tf.float32)

# Reshape weights to match dimensions for tensordot operation
# Weights need to be reshaped to [1, 3, 1, 1] for broadcasting with feature_maps
weights_reshaped = tf.reshape(weights, [1, 3, 1, 1])

# Compute the weighted sum of feature maps for each image
# Shape of feature_maps: [2, 3, 4, 4]
# Shape of weights_reshaped: [1, 3, 1, 1]
# Resulting shape will be [2, 4, 4] for aggregated scores
aggregated_scores = tf.reduce_sum(feature_maps * weights_reshaped, axis=1)

# Print the resulting combined scores
print("Combined Scores for Each Image:")
print(aggregated_scores.numpy())


Combined Scores for Each Image:
[[[ 3.  5.  4.  6.]
  [ 6.  8.  7.  9.]
  [ 9. 11. 10. 12.]
  [12. 14. 13. 15.]]

 [[ 6.  8.  7.  9.]
  [ 9. 11. 10. 12.]
  [12. 14. 13. 15.]
  [15. 17. 16. 18.]]]


### Understanding of output

**In Image 1's combined score matrix, each value represents the weighted sum of pixel values from edges, textures, and colors feature maps at that position. For example, the top-left value (3) and bottom-right value (15) reflect the summed importance of features at those specific pixels.**

## Indexing

In [24]:
# Define a tensor with integer values
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])

# Print the entire tensor
print(x[:])      # Output: [0, 1, 1, 2, 3, 1, 2, 3]

# Print the tensor from index 1 to the end
print(x[1:])     # Output: [1, 1, 2, 3, 1, 2, 3]

# Print the tensor from index 1 to index 3 (exclusive)
print(x[1:3])    # Output: [1, 1]

# Print every second element from the tensor
print(x[::2])    # Output: [0, 1, 3, 2]

# Print the tensor in reverse order
print(x[::-1])   # Output: [3, 2, 1, 3, 2, 1, 1, 0]


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [26]:
# Define a tensor with integer values
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])

# Define indices to gather
indices = tf.constant([0, 4])

# The tf.gather function is used to gather specific elements from a tensor based on the indices provided.
# Here, it extracts elements from x at positions specified by indices [0, 3].
x_indices = tf.gather(x, indices)

# Print the gathered elements
print(x_indices)  # Output: [0 2]


tf.Tensor([0 3], shape=(2,), dtype=int32)


In [27]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
